# fly.toml app configuration file generated for novel-setting-api-production on 2023-06-13T03:31:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "novel-setting-api-production"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
