local:
  clients:
    default:
      database: local
      hosts:
        - localhost:27017
      options:
  options:
staging:
  clients:
    default:
      database: staging
      hosts:
        - staging:51180
      options:
        user: "dev"
        password: "password"
        retry_writes: false
  options:
test:
  clients:
    default:
      database: local
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
